image_ext : '.png'
label_ext : '.png'

ite_num : 0
running_loss : 0.0
running_tar_loss : 0.0
ite_num4val : 0
save_frq : 2000  # save the model every 2000 iterations
early_stopping_round : 50
epoch_num : 100
model_name : 'u2net'  # 'u2netp'
batch_size_val : 1
batch_size_train : 12
model_dir : './saved_models'
pre_model_dir : r'F:\Segmentation\SemiSeg_CPS_Torch_Darren\pretrained_model\u2net.pth'
